# Generated by Django 5.0.2 on 2025-03-01 11:31

import avatar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_avatar_dall_e_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='generated_voice',
            field=models.FileField(blank=True, null=True, upload_to=avatar.models.voice_directory_path),
        ),
        migrations.AddField(
            model_name='avatar',
            name='original_voice',
            field=models.FileField(blank=True, null=True, upload_to=avatar.models.voice_directory_path),
        ),
    ]
