# Generated by Django 5.0.2 on 2025-03-01 12:47

import avatar.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_avatar_generated_voice_avatar_original_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_photo', models.ImageField(upload_to=avatar.models.user_directory_path)),
                ('generated_avatar', models.ImageField(blank=True, null=True, upload_to=avatar.models.user_directory_path)),
                ('dall_e_url', models.URLField(blank=True, max_length=500)),
                ('original_voice', models.FileField(blank=True, null=True, upload_to=avatar.models.voice_directory_path)),
                ('generated_voice', models.FileField(blank=True, null=True, upload_to=avatar.models.voice_directory_path)),
                ('prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_saved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
