# Generated by Django 5.0.2 on 2025-03-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0005_user_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dall_e_url',
        ),
    ]
